$=s=>document.querySelector(s)
const styled = {
    main:[
        {
            el:'#coverColor',
            property:'background',
            unit:'',
            to:'.cover-bg'
        },
        {
            el:'#boxColor',
            property:'background',
            unit:'',
            to:'#box'
        },
        {
            el:'#boxW',
            property:'width',
            unit:'px',
            to:'#box'
        },
        {
            el:'#boxH',
            property:'height',
            unit:'px',
            to:'#box'
        },
        {
            el:'#borderW',
            property:'borderWidth',
            unit:'px',
            to:'#box'
        },
        {
            el:'#borderR',
            property:'borderRadius',
            unit:'px',
            to:'#box'
        },
        {
            el:'#borderC',
            property:'borderColor',
            unit:'',
            to:'#box'
        },
        {
            el:'#textColor',
            property:'color',
            unit:'',
            to:'#box'
        },
        {
            el:'#fontSize',
            property:'fontSize',
            unit:'px',
            to:'#box'
        },
        {
            el:'#fontWeight',
            property:'fontWeight',
            unit:'',
            to:'#box'
        },
        {
            el:'#textTransform',
            property:'textTransform',
            unit:'',
            to:'#box'
        },
        {
            el:'#textDecoration',
            property:'textDecoration',
            unit:'',
            to:'#box'
        },
        {
            el:'#rotate',
            property:'rotate',
            unit:'deg',
            to:'#box'
        },
        {
            el:'#scale',
            property:'scale',
            unit:'',
            to:'#box'
        },
        {
            el:'#transitionTime',
            property:'transitionDuration',
            unit:'s',
            to:'#box'
        }
    ],
    shadow:{
       values:['#000000','0px','0px','0px','0px'],
        to:'#box',
        elements:[
            {
                el:'#shColor',
                index:0,
                unit:'',
            },
            {
                el:'#shX',
                index:1,
                unit:'px',
            },
            {
                el:'#shY',
                index:2,
                unit:'px',
            },
            {
                el:'#shBlur',
                index:3,
                unit:'px',
            },
            {
                el:'#shSpread',
                index:4,
                unit:'px',
            }
        ]
    }
}
styled.main.forEach(obj=>{
$(obj.el).oninput=function(e){
     $(obj.to).style[obj.property]=e.target.value+obj.unit;
 }
})
styled.shadow.elements.forEach(obj=>{
    $(obj.el).oninput=function(e){
        styled.shadow.values[obj.index]=e.target.value+obj.unit;
        $(styled.shadow.to).style.boxShadow=styled.shadow.values.join(' ')
    }
})